language: php
sudo: false
php:
    - 7.3
    - 7.4
    - 8.0
    - 8.1
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - travis_retry composer self-update
install:
  - travis_retry composer update --no-interaction --prefer-source
script:
  - composer test
